framework:
    workflows:
        sponsorship:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Sponsorship
            initial_marking: initialized
            places:
                - initialized
                - in_progress
                - ended

            transitions:
                to_in_progress:
                    from: initialized
                    to: in_progress
                to_ended: # L'un des parti souhaite arrêter le parrainnage
                    from: in_progress
                    to: ended

        lead:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Lead
            initial_marking: free
            places:
                - free
                - not_satisfiable
                - blocked
                - sponsorized
                - archived
            transitions:
                to_blocked:
                    from: free
                    to: blocked
                to_not_satisfiable:
                    from: blocked
                    to: not_satisfiable
                to_free:
                    from: [blocked, archived, sponsorized]
                    to: free
                to_sponsorized:
                    from: [blocked, archived]
                    to: sponsorized
                to_archived:
                    from: sponsorized
                    to: archived